import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 10)
#df = pd.read_excel('data01.xlsx', sheet_name="Sheet1")
#df = df.sort_values(by='Item')
#df = df.sort_values(by='Item', ascending=False)
#df = df.sort_values(by='Item', ascending=True)
#df = df.sort_values(by='kingaku', ascending=True)
#df = df.sort_values(by='kingaku', ascending=False)
#df = df.sort_values(by=['tanka', 'kingaku'])
#df = df.sort_values(by=['tanka', 'kingaku'], ascending=[True, False])
#df = df.sort_values(by=['Item', 'tanka', 'kingaku'], ascending=[False, True, False])
#df = pd.read_excel('data01.xlsx', sheet_name="Sheet2")
#df = df.sort_values(by='suuryou', ascending=True)
#df = df.sort_values(by='suuryou', ascending=False)
#df = df.sort_values(by='suuryou', ascending=False, na_position='first')

df_ax = pd.DataFrame({'col01':[1, 4, 7], 'col02':[2, 5, 8], "col03":[3, 6, 9]}
                     ,index=['idx01', 'idx02', 'idx03'])
print(df_ax)
#print(df_ax.sort_values(by='idx01', ascending=False, axis=1)) 
#ならないけど。。。-> print()で囲む
#print(df_ax.sort_values(by='col01', ascending=False, axis=0))
#print(df_ax.sort_values(by='idx02', ascending=False, axis=1))
#print(df_ax.sort_values(by='col01', ascending=False))
#df_ax = df_ax.sort_values(by='col01', ascending=False)
#print(df_ax.sort_values(by='col01', ascending=False, inplace=True))
#print(df_ax.sort_index(ascending=False))
#df_ax = df_ax.sort_index(ascending=False, inplace=True, na_position='first')
#print(df_ax.sort_index(axis=1,ascending=False))
s = df_ax['col01']
print(s)
#s = s.sort_values(ascending=False)
#s = s.sort_index(ascending=True)
print(s.sort_index(ascending=False))
#print(s)
#print(type(s))
#print(df_ax)