import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 5)
df=pd.read_csv("c01.csv", encoding="shift-jis")
df.index=df.index + 1
#print(df[["都道府県名", "人口（総数）"]][:5])
#print(df[df["都道府県名"]=="東京都"])
#print(df["西暦（年）"] % 10 == 0)
#print(df[df["西暦（年）"] % 10 == 0])
#print(df[~(df["西暦（年）"] % 10 == 0)])
#print(df[df["西暦（年）"] % 10 != 0])
#print(df[(df["西暦（年）"]==2015) & (df["都道府県名"]=="東京都")])
#print(df[(df["西暦（年）"]==2010) | (df["西暦（年）"]==2015)])
df = df.rename(columns={"西暦（年）": "year"})
print(df)
#print(df.query("year == 2010"))
#print(df.query("year > 2010"))
#print(df.query('都道府県名 == "東京都"'))
#print(df.query("year == 2010 or year == 2015"))
#print(df.query('都道府県名 == "東京都" and year == 2015'))
#print(df['year'].isin([2010]))
#print(df[df['year'].isin([2010])])
#print(df[df['year'].isin([2010, 2015])])
#print(df['都道府県名'].str.contains('山'))
#print(df[df['都道府県名'].str.contains('山', na=False)])
#print(df[df['都道府県名'].str.startswith('大', na=False)])
#print(df[df['都道府県名'].str.endswith('道', na=False)])
#print(df[df['year'] == df['year'].max()])
#print(df[df['year'] == df['year'].min()])
print(df.loc[895, ['人口（男）', '人口（女）']])
